### ISSUE TITLE
使用uni-request请求，data数据中如果存在数组的问题

### ISSUE THREAD

**Issue by ghsssss** [QzeroQ/uni-request#1]
data:{a:[1，2，3，4]}会变成data:{a:{0:1,1:2,2:3,3:4}}

**Comment by thx125** [comment]
可以通过修改util.js这个文件里面的merge、deepMerge方法
`export const merge = function() {
  var result = {};
  Array.from(arguments).forEach(e => {
    for (let key in e) {
      if (!e[key] instanceof Array && typeof e[key] === 'object' && !isEmptyObject(e[key])) {
        merge(result[key], e[key])
      }
      result[key] = e[key]
    }
  });
  return result;
}



export const deepMerge = function() {
  let result = {};
  Array.from(arguments).forEach(e => {
    if (e && typeof e === 'object' && !isEmptyObject(e)) {
      Object.keys(e).forEach(key => {
        if (!e[key] instanceof Array && typeof e[key] === 'object') {
          return result[key] = deepMerge(result[key], e[key])
        }
        result[key] = e[key]
      });
    }
  })
  return result;
}`

**Comment by ghsssss** [comment]
谢谢
